use_frameworks!

platform :ios, '8.0'

target 'FCCategoryOCKit_Example' do
  pod 'FCCategoryOCKit', :path => '../'

  target 'FCCategoryOCKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
